// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALWcGUf3afOs4K-Fr8Q8FAbBJ_gsjauiA',
    appId: '1:874657566001:web:304d91f64b9bcc1dbf7410',
    messagingSenderId: '874657566001',
    projectId: 'fyp26-a22b9',
    authDomain: 'fyp26-a22b9.firebaseapp.com',
    storageBucket: 'fyp26-a22b9.firebasestorage.app',
    measurementId: 'G-CL604XBQ9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0uRs2j2AyGsr_vz6zm5hvJsmPvyt00uc',
    appId: '1:874657566001:android:03bdd215d0ca9816bf7410',
    messagingSenderId: '874657566001',
    projectId: 'fyp26-a22b9',
    storageBucket: 'fyp26-a22b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEbFRVoJmGD6piczD78bP4PDOJalwZA-s',
    appId: '1:1073333582888:ios:0a8ce7f6aa97fb5043491d',
    messagingSenderId: '1073333582888',
    projectId: 'dental-care-6daf8',
    storageBucket: 'dental-care-6daf8.appspot.com',
    iosBundleId: 'com.example.dentalCare',
  );
}