// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Iq3I5oaCmGjesX75r3Q_SHOhEA8YSqY',
    appId: '1:1073333582888:web:8166baf5019224f243491d',
    messagingSenderId: '1073333582888',
    projectId: 'dental-care-6daf8',
    authDomain: 'dental-care-6daf8.firebaseapp.com',
    storageBucket: 'dental-care-6daf8.firebasestorage.app',
    measurementId: 'G-04DZKJFC3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYfLK7ewivGmUsy8DYu1-pXSbtlwcwIWo',
    appId: '1:1073333582888:android:747ed956a0b24d9e43491d',
    messagingSenderId: '1073333582888',
    projectId: 'dental-care-6daf8',
    storageBucket: 'dental-care-6daf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEbFRVoJmGD6piczD78bP4PDOJalwZA-s',
    appId: '1:1073333582888:ios:0a8ce7f6aa97fb5043491d',
    messagingSenderId: '1073333582888',
    projectId: 'dental-care-6daf8',
    storageBucket: 'dental-care-6daf8.firebasestorage.app',
    iosBundleId: 'com.example.dentalCare',
  );
}
