import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../../../models/scan_model.dart';
import 'package:intl/intl.dart';

class PdfExportService {
  static Future<void> exportDiagnosticReport(ScanModel scan, Uint8List imageBytes) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('PalPath AI', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.blue800)),
                  pw.Text('Clinical Diagnostic Report', style: const pw.TextStyle(fontSize: 14, color: PdfColors.grey700)),
                ],
              ),
              pw.SizedBox(height: 20),
              pw.Divider(),
              pw.SizedBox(height: 10),

              // Patient Info
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Patient Name: ${scan.patientName}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 14)),
                      pw.Text('Scan Date: ${DateFormat('dd MMM yyyy').format(scan.scanDate)}'),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text('Scan Type: ${scan.scanType}'),
                      pw.Text('Status: ${scan.statusLabel}'),
                    ],
                  ),
                ],
              ),
              pw.SizedBox(height: 20),

              // X-Ray Image
              if (imageBytes.isNotEmpty)
                pw.Center(
                  child: pw.Container(
                    height: 200,
                    child: pw.Image(pw.MemoryImage(imageBytes)),
                  ),
                ),
              pw.SizedBox(height: 20),

              // Findings
              pw.Text('Diagnostic Findings', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 8),
              if (scan.findings.isEmpty)
                pw.Text('No abnormalities detected.')
              else
                pw.TableHelper.fromTextArray(
                  headers: ['Finding', 'Confidence'],
                  data: scan.findings.map((f) => [f.label, '${(f.confidence * 100).toStringAsFixed(1)}%']).toList(),
                  border: pw.TableBorder.all(color: PdfColors.grey300),
                  headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                  headerDecoration: const pw.BoxDecoration(color: PdfColors.grey100),
                ),

              pw.SizedBox(height: 20),

              // Prescription
              if (scan.prescription != null) ...[
                pw.Text('Clinical Prescription', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 8),
                pw.Container(
                  padding: const pw.EdgeInsets.all(12),
                  decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.grey300)),
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Diagnosis: ${scan.prescription!.diagnosis}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                      pw.SizedBox(height: 4),
                      pw.Text('Rx: ${scan.prescription!.prescription}'),
                      pw.SizedBox(height: 4),
                      pw.Text('Follow-up: ${scan.prescription!.followUp}'),
                      pw.SizedBox(height: 4),
                      pw.Text('Precautions: ${scan.prescription!.precautions}'),
                    ],
                  ),
                )
              ],

              pw.Spacer(),
              pw.Divider(),
              pw.Center(
                child: pw.Text('Generated by PalPath AI · ${DateFormat('dd MMM yyyy HH:mm').format(DateTime.now())}', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
              ),
            ],
          );
        },
      ),
    );

    await Printing.sharePdf(bytes: await pdf.save(), filename: 'scan_${scan.id}.pdf');
  }
}
