import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';

import '../models/case_model.dart';
import '../models/prescription_model.dart';

Future<Uint8List> generateCasePdf(CaseModel c, PrescriptionModel? rx) async {
  final pdf = pw.Document();
  final image = c.imageUrls.isNotEmpty
    ? await networkImage(c.imageUrls.first)
    : null;

  pdf.addPage(pw.MultiPage(
    pageFormat: PdfPageFormat.a4,
    build: (ctx) => [
      // Header
      pw.Row(children: [
        pw.Text('PalPath', style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
        pw.Spacer(),
        pw.Text('Dental Diagnostic Report', style: const pw.TextStyle(fontSize: 11)),
      ]),
      pw.Divider(),

      // Patient info
      pw.Text('Patient: ${c.patientName}', style: const pw.TextStyle(fontSize: 13)),
      pw.Text('Scan Date: ${DateFormat('d MMMM yyyy, HH:mm').format(c.caseDate)}'),
      pw.Text('Case ID: ${c.id}'),
      pw.SizedBox(height: 12),

      // X-ray image
      if (image != null) ...[
        pw.Text('Panoramic X-ray', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 6),
        pw.Image(image, height: 180),
        pw.SizedBox(height: 12),
      ],

      // AI findings
      pw.Text('AI Diagnostic Findings', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
      pw.SizedBox(height: 4),
      pw.Text('Status: ${c.analysisResults.status}'),
      pw.Text('Confidence: ${(c.analysisResults.confidence * 100).toStringAsFixed(1)}%'),
      pw.Text('Cavity Detected: ${c.analysisResults.hasCavity ? "Yes" : "No"}'),
      pw.Text('Details: ${c.analysisResults.details}'),
      pw.SizedBox(height: 16),

      // Prescription
      if (rx != null) ...[
        pw.Divider(),
        pw.Text('Prescription', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 14)),
        pw.SizedBox(height: 8),
        _pdfSection('Diagnosis', rx.diagnosis),
        _pdfSection('Prescription', rx.prescription),
        _pdfSection('Follow-up Treatment', rx.followUpTreatment),
        _pdfSection('Precautions', rx.precautions),
        pw.SizedBox(height: 8),
        pw.Text('Written by: ${rx.dentistName} · ${DateFormat('d MMM yyyy').format(rx.createdAt)}',
          style: const pw.TextStyle(fontSize: 10)),
      ],

      // Footer
      pw.SizedBox(height: 20),
      pw.Divider(),
      pw.Text('Generated by PalPath AI · ${DateFormat('d MMM yyyy, HH:mm').format(DateTime.now())}',
        style: const pw.TextStyle(fontSize: 9)),
    ],
  ));

  return pdf.save();
}

pw.Widget _pdfSection(String label, String value) => pw.Column(
  crossAxisAlignment: pw.CrossAxisAlignment.start,
  children: [
    pw.Text(label, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11)),
    pw.Text(value, style: const pw.TextStyle(fontSize: 10)),
    pw.SizedBox(height: 8),
  ],
);
